import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

// style sheet
import "./globals.css";
import "./style.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-40">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
